version: "2"
services:
  netlifycms:
    container_name: netlify-cms-oauth
    restart: unless-stopped
    image: rori4/netlify-cms-github-oauth-provider
    ports:
      - 80:80
    environment:
      NODE_ENV: production
      ORIGIN: http://localhost:3000
      OAUTH_CLIENT_ID: <client_id>
      OAUTH_CLIENT_SECRET: <client_secret>
      PORT: 80
    volumes:
      - netlifycms:/var/netlify/oauth
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - sslcerts:/etc/ssl/private
    depends_on:
      - netlifycms
    entrypoint:
      - "bash"
      - "-c"
    command: |
      "if [ ! -f /etc/ssl/private/netlifycms.crt ]; then
        echo 'ssl certificate missing, installing openssl to create a new one'
        apt-get update && apt-get install openssl -y
        openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout /etc/ssl/private/netlifycms.key -out /etc/ssl/private/netlifycms.crt -subj '/CN=netlifycms.local' -days 3650
        echo 'Created new ssl certificate'
      fi
      exec nginx -g 'daemon off;'"
volumes:
  netlifycms:
  sslcerts: